name: astral
description: "astral"
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 2.0.0-beta.106

environment:
  sdk: ^3.7.2

dependencies:
  open_file: ^3.0.0
  vpn_service_plugin:
    path: vpn_service_plugin
  flutter:
    sdk: flutter
  path: ^1.8.3  # Add this line
  cupertino_icons: ^1.0.8
  rust_lib_astral:
    path: rust_builder
  flutter_rust_bridge: 2.10.0
  signals_flutter: ^6.0.2
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  window_manager: ^0.4.3
  flutter_colorpicker: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^3.0.7
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^3.2.0
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  graphview: ^1.2.0
  device_info_plus: ^11.4.0
  toml: ^0.16.0
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  system_tray: ^2.0.3
  app_links: ^6.4.0
  sentry_flutter: ^8.14.2
  flutter_dotenv: ^5.2.1
  win32: ^5.12.0
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8

flutter:
  uses-material-design: true
  assets:
    # - assets/dlls/
    - assets/icon.ico
  
  fonts:
    - family: MiSans
      fonts:
          - asset: fonts/MiSans-Demibold.ttf
          - asset: fonts/MiSans-Regular.ttf
            weight: 800
