name: ğŸ› ï¸ Android æ„å»º armeabi-v7a æ¶æ„ APK

on:
  workflow_call: {}  # å…è®¸è¢«å…¶ä»–å·¥ä½œæµè°ƒç”¨

jobs:
  build-armv7:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: ğŸ› ï¸ æ£€å‡ºä»£ç ä»“åº“
        uses: actions/checkout@v4

      - name: ğŸ¦ è®¾ç½® Flutter
        run: |
          export PATH="$HOME/flutter/bin:$PATH"
          echo "PATH: $PATH"
          which flutter
          flutter --version

      - name: ğŸ› ï¸ æ„å»º armeabi-v7a æ¶æ„ APK
        run: |
          flutter build apk --release --target-platform android-arm

      - name: ğŸ“¤ ä¸Šä¼  armeabi-v7a æ¶æ„ APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
