name: ğŸš€ Android ä¸»å·¥ä½œæµ

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› ï¸ åˆå§‹åŒ–
        run: echo "ğŸš€ å¼€å§‹ Android ä¸»å·¥ä½œæµ"

  setup:
    needs: init
    uses: ./.github/workflows/android-setup.yaml

  build-all:
    needs: setup
    uses: ./.github/workflows/android-build-all.yaml

  build-x86:
    needs: setup
    uses: ./.github/workflows/android-build-x86.yaml

  build-x86_64:
    needs: setup
    uses: ./.github/workflows/android-build-x86_64.yaml

  build-arm64:
    needs: setup
    uses: ./.github/workflows/android-build-arm64.yaml

  build-armv7:
    needs: setup
    uses: ./.github/workflows/android-build-armv7.yaml
