name: ğŸ› ï¸ Android æ„å»ºå…¨æ¶æ„ APK

on:
  workflow_call: {}  # å…è®¸è¢«å…¶ä»–å·¥ä½œæµè°ƒç”¨

jobs:
  build-all:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: ğŸ› ï¸ æ£€å‡ºä»£ç ä»“åº“
        uses: actions/checkout@v4

      - name: ğŸ¦ è®¾ç½® Flutter
        run: |
          export PATH="$HOME/flutter/bin:$PATH"
          echo "PATH: $PATH"
          which flutter
          flutter --version

      - name: ğŸ› ï¸ æ„å»ºå…¨æ¶æ„ APK (ALL)
        run: |
          flutter build apk --release

      - name: ğŸ“¤ ä¸Šä¼ å…¨æ¶æ„ APK (ALL)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-all
          path: build/app/outputs/flutter-apk/app-release.apk
